### ISSUE TITLE
apscheduler.executors.default - ERROR - Job "BountyAgent.job

### ISSUE THREAD

**Issue by Nikolay-everstake** [skalenetwork/bounty-agent#123]
When bounty-agent got bounty it got this error that I can see in log.
2021-01-29 00:17:42,300 - bounty-agent - INFO - The bounty was successfully received
2021-01-29 00:17:42,302 - apscheduler.executors.default - ERROR - Job "BountyAgent.job (trigger: date[2021-01-29 00:17:15 UTC], next run at: 2021-01-29 00:17:15 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(_job.args, *_job.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/tenacity/**init**.py", line 329, in wrapped_f
    return self.call(f, _args, *_kw)
  File "/usr/local/lib/python3.7/dist-packages/tenacity/**init**.py", line 409, in call
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.7/dist-packages/tenacity/**init**.py", line 356, in iter
    return fut.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.7/dist-packages/tenacity/**init**.py", line 412, in call
    result = fn(_args, *_kwargs)
  File "bounty_agent.py", line 122, in job
    self.get_bounty()
  File "bounty_agent.py", line 92, in get_bounty
    h_receipt = self.skale.manager.contract.events.BountyReceived().processReceipt(
  File "/usr/local/lib/python3.7/dist-packages/web3/contract.py", line 244, in **getattr**
    "Are you sure you provided the correct contract abi?"
web3.exceptions.MismatchedABI: ("The event 'BountyReceived' was not found in this contract's abi. ", 'Are you sure you provided the correct contract abi?')
2021-01-29 00:17:42,303 - bounty-agent - INFO - The job failed
2021-01-29 00:17:42,304 - apscheduler.scheduler - INFO - Added job "BountyAgent.job" to job store "default"
2021-01-29 00:18:42,305 - apscheduler.scheduler - INFO - Removed job 4e03e526fe274d7d84ce86a9fa080dad
2021-01-29 00:18:42,305 - apscheduler.executors.default - INFO - Running job "BountyAgent.job (trigger: date[2021-01-29 00:18:42 UTC], next run at: 2021-01-29 00:18:42 UTC)" (scheduled at 2021-01-29 00:18:42.304160+00:00)

┆Issue is synchronized with this [Jira Task](https://skalelabs.atlassian.net/browse/SKALE-3836)

**Comment by gannakulikova** [comment]
Hi @Nikolay-everstake !
Thank you for reaching out! Please be advised that this issue is fixed from the dev perspective and will be a part of the next SKALE Node Mainnet release - please stay tuned for the updates :)
